name: Continuos deployment

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ“¥ Checkout repository
              uses: actions/checkout@v4

            - name: ğŸŸ¨ Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: ğŸ“¥ Install deps
              run: npm i
              working-directory: ./server

            - name: ğŸ” Build project
              run: npm run build
              working-directory: ./server

            - name: ğŸŒ Set up ssh
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: ğŸŒ Delete previous build
              run: ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} "sudo rm -rf ./PetCareApi"

            - name: ğŸŒ Send build
              run: scp -r ./server/dist ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:~/PetCareApi

            - name: ğŸ§ Deploy via SSH
              run: |
                  ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
                  cd ~/PetCareApi
                  echo "${ENV_CONFIG}" > .env
                  sudo docker compose up --build -d
                  EOF
              env:
                  ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
